# Generated by Django 6.0.2 on 2026-02-08 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Optional name (leave blank to post anonymously)', max_length=50)),
                ('text', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating from 1 to 5')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='guns.gun')),
            ],
        ),
    ]
