# Generated by Django 6.0.2 on 2026-02-13 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guns', '0002_category_gun_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
