# Generated by Django 6.0.2 on 2026-02-15 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guns', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gun',
            options={'ordering': ['name']},
        ),
    ]
