# Generated by Django 6.0.2 on 2026-02-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guns', '0004_alter_gun_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='gun',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='guns/'),
        ),
    ]
